## Povezivanje, spajanje i pivot pandas tabela

## MERGE (JOIN)

In [26]:
pd.set_option("display.max_rows",None)

In [27]:
import pandas as pd

In [28]:
studenti = pd.read_excel("Fakultet.xlsx", sheet_name = "Studenti", index_col = 'student_id')
profesori = pd.read_excel("Fakultet.xlsx", sheet_name = "Profesori", index_col = 'profesor_id')
predmeti = pd.read_excel("Fakultet.xlsx", sheet_name = "Predmeti", index_col = 'predmet_id')
ocene = pd.read_excel("Fakultet.xlsx", sheet_name = "Ocene", index_col = 'ocena_id')

In [ ]:
studenti.head()

In [ ]:
studenti_ocene = studenti.merge(ocene, how = 'inner', on = "student_id")

In [ ]:
studenti_ocene

In [30]:
studenti_ocene = studenti.merge(ocene, how = 'left', on = "student_id")

In [31]:
studenti_ocene

    student_id        ime      prezime       grad  predmet_id  ocena
0            1     Milica  Slijepcevic   Novi Sad         2.0   10.0
1            1     Milica  Slijepcevic   Novi Sad         3.0    7.0
2            1     Milica  Slijepcevic   Novi Sad         5.0    8.0
3            1     Milica  Slijepcevic   Novi Sad         7.0    8.0
4            1     Milica  Slijepcevic   Novi Sad         8.0    9.0
5            1     Milica  Slijepcevic   Novi Sad        10.0    7.0
6            2     Jovana        Arsic    Beograd         4.0    6.0
7            2     Jovana        Arsic    Beograd         5.0    9.0
8            3   Ljiljana      Nikolic    Pancevo         2.0    9.0
9            3   Ljiljana      Nikolic    Pancevo         7.0    9.0
10           4       Ivan     Ivanovic   Kraljevo         1.0   10.0
11           4       Ivan     Ivanovic   Kraljevo         3.0    7.0
12           4       Ivan     Ivanovic   Kraljevo         4.0    9.0
13           4       Ivan     Ivanovic   Kraljevo         5.0    7.0
14           4       Ivan     Ivanovic   Kraljevo         7.0    9.0
15           4       Ivan     Ivanovic   Kraljevo        12.0    6.0
16           5      Petar     Petrovic   Novi Sad         NaN    NaN
17           6      Jovan    Jovanovic   Novi Sad         1.0   10.0
18           6      Jovan    Jovanovic   Novi Sad         4.0   10.0
19           6      Jovan    Jovanovic   Novi Sad         5.0   10.0
20           6      Jovan    Jovanovic   Novi Sad         6.0   10.0
21           6      Jovan    Jovanovic   Novi Sad         7.0    7.0
22           6      Jovan    Jovanovic   Novi Sad         8.0    6.0
23           6      Jovan    Jovanovic   Novi Sad         9.0    8.0
24           6      Jovan    Jovanovic   Novi Sad        10.0    8.0
25           6      Jovan    Jovanovic   Novi Sad        11.0    9.0
26           6      Jovan    Jovanovic   Novi Sad        12.0   10.0
27           7      Ivana    Jovanovic   Novi Sad         1.0    6.0
28           7      Ivana    Jovanovic   Novi Sad         2.0    9.0
29           7      Ivana    Jovanovic   Novi Sad         5.0    9.0
30           8     Stevan        Micic   Subotica         5.0    7.0
31           8     Stevan        Micic   Subotica         6.0   10.0
32           9      Milan   Mladenovic  Zrenjanin         2.0    8.0
33          10     Mladen    Mijatovic   Novi Sad         2.0   10.0
34          10     Mladen    Mijatovic   Novi Sad         7.0    9.0
35          11      Petar     Ivanovic   Novi Sad         2.0    8.0
36          11      Petar     Ivanovic   Novi Sad         8.0   10.0
37          11      Petar     Ivanovic   Novi Sad        10.0    8.0
38          11      Petar     Ivanovic   Novi Sad        11.0    6.0
39          12     Jovana       Pavlov   Novi Sad         3.0    8.0
40          12     Jovana       Pavlov   Novi Sad         4.0   10.0
41          12     Jovana       Pavlov   Novi Sad         6.0    9.0
42          12     Jovana       Pavlov   Novi Sad         8.0    7.0
43          12     Jovana       Pavlov   Novi Sad        10.0    8.0
44          12     Jovana       Pavlov   Novi Sad        11.0    9.0
45          13    Biljana       Ninkov   Subotica         1.0    9.0
46          13    Biljana       Ninkov   Subotica         2.0    7.0
47          13    Biljana       Ninkov   Subotica         4.0    9.0
48          13    Biljana       Ninkov   Subotica         6.0   10.0
49          13    Biljana       Ninkov   Subotica         7.0    6.0
50          13    Biljana       Ninkov   Subotica        12.0    8.0
51          14       Maja       Doslic   Subotica         4.0    7.0
52          15    Snezana        Delic   Novi Sad         5.0    8.0
53          15    Snezana        Delic   Novi Sad         7.0    9.0
54          15    Snezana        Delic   Novi Sad         9.0   10.0
55          15    Snezana        Delic   Novi Sad        11.0    9.0
56          16      Ratko   Djordjevic   Novi Sad         8.0    6.0
57          16      Ratko   Djordjevic   Novi Sad         9.0    7.0
58          16      Ratko   Djordjevic   Novi Sad        11.0    6.0
59          17      Todor        Josic   Novi Sad         NaN    NaN
60          18       Luka        Lucic   Novi Sad         1.0   10.0
61          18       Luka        Lucic   Novi Sad         2.0    7.0
62          18       Luka        Lucic   Novi Sad         3.0    8.0
63          18       Luka        Lucic   Novi Sad         4.0   10.0
64          19      Marko     Markovic  Zrenjanin         NaN    NaN
65          20  Dimitrije    Radulovic   Novi Sad         2.0    6.0

In [32]:
stu_oce_pred = studenti_ocene.merge(predmeti, how = 'inner', on = 'predmet_id')

In [33]:
stu_oce_pred

,student_id,ime,prezime,grad,predmet_id,ocena,naziv,espb_poeni,id_profesora
0,1,Milica,Slijepcevic,Novi Sad,2.0,10.0,Uvod u programiranje,6,2
1,3,Ljiljana,Nikolic,Pancevo,2.0,9.0,Uvod u programiranje,6,2
2,7,Ivana,Jovanovic,Novi Sad,2.0,9.0,Uvod u programiranje,6,2
3,9,Milan,Mladenovic,Zrenjanin,2.0,8.0,Uvod u programiranje,6,2
4,10,Mladen,Mijatovic,Novi Sad,2.0,10.0,Uvod u programiranje,6,2
5,11,Petar,Ivanovic,Novi Sad,2.0,8.0,Uvod u programiranje,6,2
6,13,Biljana,Ninkov,Subotica,2.0,7.0,Uvod u programiranje,6,2
7,18,Luka,Lucic,Novi Sad,2.0,7.0,Uvod u programiranje,6,2
8,20,Dimitrije,Radulovic,Novi Sad,2.0,6.0,Uvod u programiranje,6,2
9,1,Milica,Slijepcevic,Novi Sad,3.0,7.0,Socijologija tehnike,2,5
10,4,Ivan,Ivanovic,Kraljevo,3.0,7.0,Socijologija tehnike,2,5
11,12,Jovana,Pavlov,Novi Sad,3.0,8.0,Socijologija tehnike,2,5
12,18,Luka,Lucic,Novi Sad,3.0,8.0,Socijologija tehnike,2,5
13,1,Milica,Slijepcevic,Novi Sad,5.0,8.0,Engleski 2,3,3
14,2,Jovana,Arsic,Beograd,5.0,9.0,Engleski 2,3,3
15,4,Ivan,Ivanovic,Kraljevo,5.0,7.0,Engleski 2,3,3
16,6,Jovan,Jovanovic,Novi Sad,5.0,10.0,Engleski 2,3,3
17,7,Ivana,Jovanovic,Novi Sad,5.0,9.0,Engleski 2,3,3
18,8,Stevan,Micic,Subotica,5.0,7.0,Engleski 2,3,3
19,15,Snezana,Delic,Novi Sad,5.0,8.0,Engleski 2,3,3
20,1,Milica,Slijepcevic,Novi Sad,7.0,8.0,Algebra,5,7
21,3,Ljiljana,Nikolic,Pancevo,7.0,9.0,Algebra,5,7
22,4,Ivan,Ivanovic,Kraljevo,7.0,9.0,Algebra,5,7
23,6,Jovan,Jovanovic,Novi Sad,7.0,7.0,Algebra,5,7
24,10,Mladen,Mijatovic,Novi Sad,7.0,9.0,Algebra,5,7
25,13,Biljana,Ninkov,Subotica,7.0,6.0,Algebra,5,7
26,15,Snezana,Delic,Novi Sad,7.0,9.0,Algebra,5,7
27,1,Milica,Slijepcevic,Novi Sad,8.0,9.0,Objektno orijentisano programiranje,6,2
28,6,Jovan,Jovanovic,Novi Sad,8.0,6.0,Objektno orijentisano programiranje,6,2
29,11,Petar,Ivanovic,Novi Sad,8.0,10.0,Objektno orijentisano programiranje,6,2
30,12,Jovana,Pavlov,Novi Sad,8.0,7.0,Objektno orijentisano programiranje,6,2
31,16,Ratko,Djordjevic,Novi Sad,8.0,6.0,Objektno orijentisano programiranje,6,2
32,1,Milica,Slijepcevic,Novi Sad,10.0,7.0,Fizika,4,12
33,6,Jovan,Jovanovic,Novi Sad,10.0,8.0,Fizika,4,12
34,11,Petar,Ivanovic,Novi Sad,10.0,8.0,Fizika,4,12
35,12,Jovana,Pavlov,Novi Sad,10.0,8.0,Fizika,4,12
36,2,Jovana,Arsic,Beograd,4.0,6.0,Engleski 1,3,3
37,4,Ivan,Ivanovic,Kraljevo,4.0,9.0,Engleski 1,3,3
38,6,Jovan,Jovanovic,Novi Sad,4.0,10.0,Engleski 1,3,3
39,12,Jovana,Pavlov,Novi Sad,4.0,10.0,Engleski 1,3,3
40,13,Biljana,Ninkov,Subotica,4.0,9.0,Engleski 1,3,3
41,14,Maja,Doslic,Subotica,4.0,7.0,Engleski 1,3,3
42,18,Luka,Lucic,Novi Sad,4.0,10.0,Engleski 1,3,3
43,4,Ivan,Ivanovic,Kraljevo,1.0,10.0,Baze podataka,6,1
44,6,Jovan,Jovanovic,Novi Sad,1.0,10.0,Baze podataka,6,1
45,7,Ivana,Jovanovic,Novi Sad,1.0,6.0,Baze podataka,6,1
46,13,Biljana,Ninkov,Subotica,1.0,9.0,Baze podataka,6,1
47,18,Luka,Lucic,Novi Sad,1.0,10.0,Baze podataka,6,1
48,4,Ivan,Ivanovic,Kraljevo,12.0,6.0,Diskretna matematika,4,7
49,6,Jovan,Jovanovic,Novi Sad,12.0,10.0,Diskretna matematika,4,7
50,13,Biljana,Ninkov,Subotica,12.0,8.0,Diskretna matematika,4,7
51,6,Jovan,Jovanovic,Novi Sad,6.0,10.0,Analiza,5,7
52,8,Stevan,Micic,Subotica,6.0,10.0,Analiza,5,7
53,12,Jovana,Pavlov,Novi Sad,6.0,9.0,Analiza,5,7
54,13,Biljana,Ninkov,Subotica,6.0,10.0,Analiza,5,7
55,6,Jovan,Jovanovic,Novi Sad,9.0,8.0,Masinsko ucenje,4,8
56,15,Snezana,Delic,Novi Sad,9.0,10.0,Masinsko ucenje,4,8
57,16,Ratko,Djordjevic,Novi Sad,9.0,7.0,Masinsko ucenje,4,8
58,6,Jovan,Jovanovic,Novi Sad,11.0,9.0,Algoritmi i strukture podataka,5,10
59,11,Petar,Ivanovic,Novi Sad,11.0,6.0,Algoritmi i strukture podataka,5,10
60,12,Jovana,Pavlov,Novi Sad,11.0,9.0,Algoritmi i strukture podataka,5,10
61,15,Snezana,Delic,Novi Sad,11.0,9.0,Algoritmi i strukture podataka,5,10
62,16,Ratko,Djordjevic,Novi Sad,11.0,6.0,Algoritmi i strukture podataka,5,10

In [ ]:
studenti_ocene = studenti.merge(ocene, how = 'right', on = "student_id")

In [ ]:
studenti_ocene

In [ ]:
studenti_ocene = studenti.merge(ocene, how = 'outer', on = "student_id")

In [ ]:
studenti_ocene

In [ ]:
studenti_ocene = studenti.merge(ocene, how = 'cross')
#studenti_ocene

In [29]:
predmet_profesor = predmeti.merge(profesori, how= 'left', left_on = 'id_profesora', right_on = 'profesor_id')
predmet_profesor

,naziv,espb_poeni,id_profesora,ime,prezime,grad
0,Baze podataka,6,1,Novak,Djokovic,Novi Sad
1,Uvod u programiranje,6,2,Bogdan,Bogdanovic,Zrenjanin
2,Socijologija tehnike,2,5,Milos,Teodosic,Subotica
3,Engleski 1,3,3,Sonja,Vasic,Novi Sad
4,Engleski 2,3,3,Sonja,Vasic,Novi Sad
5,Analiza,5,7,Milica,Mandic,Beograd
6,Algebra,5,7,Milica,Mandic,Beograd
7,Objektno orijentisano programiranje,6,2,Bogdan,Bogdanovic,Zrenjanin
8,Masinsko ucenje,4,8,Zorana,Arunovic,Beograd
9,Fizika,4,12,NaN,NaN,NaN
10,Algoritmi i strukture podataka,5,10,Ivana,Spanovic,Novi Sad
11,Diskretna matematika,4,7,Milica,Mandic,Beograd

## CONCAT

In [34]:
novi_studenti = pd.read_excel("Fakultet.xlsx", sheet_name = "Novi Studenti", index_col = 'student_id')

In [36]:
novi_studenti

                ime     prezime       grad
student_id
21            Milos      Pejcic   Novi Sad
22             Luka  Marjanovic    Beograd
23            Marko   Milanovic  Zrenjanin
24          Tatjana     Mijatov   Novi Sad
25           Jovana    Markovic   Novi Sad
26           Natasa   Jovanovic   Novi Sad
27            Stasa        Ilic   Novi Sad
28            Dusan     Radulov     Sombor
29            Milan    Vlahovic    Beograd
30           Bojana   Bulatovic   Novi Sad

In [35]:
novi_i_stari = pd.concat([studenti,novi_studenti])
novi_i_stari

                  ime      prezime       grad
student_id
1              Milica  Slijepcevic   Novi Sad
2              Jovana        Arsic    Beograd
3            Ljiljana      Nikolic    Pancevo
4                Ivan     Ivanovic   Kraljevo
5               Petar     Petrovic   Novi Sad
6               Jovan    Jovanovic   Novi Sad
7               Ivana    Jovanovic   Novi Sad
8              Stevan        Micic   Subotica
9               Milan   Mladenovic  Zrenjanin
10             Mladen    Mijatovic   Novi Sad
11              Petar     Ivanovic   Novi Sad
12             Jovana       Pavlov   Novi Sad
13            Biljana       Ninkov   Subotica
14               Maja       Doslic   Subotica
15            Snezana        Delic   Novi Sad
16              Ratko   Djordjevic   Novi Sad
17              Todor        Josic   Novi Sad
18               Luka        Lucic   Novi Sad
19              Marko     Markovic  Zrenjanin
20          Dimitrije    Radulovic   Novi Sad
21              Milos       Pejcic   Novi Sad
22               Luka   Marjanovic    Beograd
23              Marko    Milanovic  Zrenjanin
24            Tatjana      Mijatov   Novi Sad
25             Jovana     Markovic   Novi Sad
26             Natasa    Jovanovic   Novi Sad
27              Stasa         Ilic   Novi Sad
28              Dusan      Radulov     Sombor
29              Milan     Vlahovic    Beograd
30             Bojana    Bulatovic   Novi Sad

In [37]:
novi_studenti['upisani'] = True

In [38]:
novi_studenti.head()

                ime     prezime       grad  upisani
student_id
21            Milos      Pejcic   Novi Sad     True
22             Luka  Marjanovic    Beograd     True
23            Marko   Milanovic  Zrenjanin     True
24          Tatjana     Mijatov   Novi Sad     True
25           Jovana    Markovic   Novi Sad     True

In [39]:
studenti.head()

                 ime      prezime      grad
student_id
1             Milica  Slijepcevic  Novi Sad
2             Jovana        Arsic   Beograd
3           Ljiljana      Nikolic   Pancevo
4               Ivan     Ivanovic  Kraljevo
5              Petar     Petrovic  Novi Sad

In [40]:
novi_i_stari = pd.concat([studenti,novi_studenti])

In [41]:
novi_i_stari

                  ime      prezime       grad upisani
student_id
1              Milica  Slijepcevic   Novi Sad     NaN
2              Jovana        Arsic    Beograd     NaN
3            Ljiljana      Nikolic    Pancevo     NaN
4                Ivan     Ivanovic   Kraljevo     NaN
5               Petar     Petrovic   Novi Sad     NaN
6               Jovan    Jovanovic   Novi Sad     NaN
7               Ivana    Jovanovic   Novi Sad     NaN
8              Stevan        Micic   Subotica     NaN
9               Milan   Mladenovic  Zrenjanin     NaN
10             Mladen    Mijatovic   Novi Sad     NaN
11              Petar     Ivanovic   Novi Sad     NaN
12             Jovana       Pavlov   Novi Sad     NaN
13            Biljana       Ninkov   Subotica     NaN
14               Maja       Doslic   Subotica     NaN
15            Snezana        Delic   Novi Sad     NaN
16              Ratko   Djordjevic   Novi Sad     NaN
17              Todor        Josic   Novi Sad     NaN
18               Luka        Lucic   Novi Sad     NaN
19              Marko     Markovic  Zrenjanin     NaN
20          Dimitrije    Radulovic   Novi Sad     NaN
21              Milos       Pejcic   Novi Sad    True
22               Luka   Marjanovic    Beograd    True
23              Marko    Milanovic  Zrenjanin    True
24            Tatjana      Mijatov   Novi Sad    True
25             Jovana     Markovic   Novi Sad    True
26             Natasa    Jovanovic   Novi Sad    True
27              Stasa         Ilic   Novi Sad    True
28              Dusan      Radulov     Sombor    True
29              Milan     Vlahovic    Beograd    True
30             Bojana    Bulatovic   Novi Sad    True

## Pivot

In [50]:
prodavnica = pd.read_excel("Prodavnica.xlsx")
prodavnica.head()

  Proizvod   Tip prodaje  Prodaja
0   Jabuka        Online      100
1   Jabuka  U prodavnici      150
2   Kruška        Online      120
3   Kruška  U prodavnici      130
4     Kivi        Online       80

In [51]:
pivot_table = prodavnica.pivot(index = 'Proizvod', columns = 'Tip prodaje', values = 'Prodaja')

In [52]:
pivot_table

Tip prodaje  Online  U prodavnici
Proizvod
Ananas           70            90
Banana           90           110
Jabuka          100           150
Kivi             80           100
Kruška          120           130
Pomorandža       80           100

In [53]:
pivot_table= pivot_table.rename_axis(None, axis=1).reset_index()
pivot_table

     Proizvod  Online  U prodavnici
0      Ananas      70            90
1      Banana      90           110
2      Jabuka     100           150
3        Kivi      80           100
4      Kruška     120           130
5  Pomorandža      80           100

In [54]:
pivot_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Proizvod      6 non-null      object
 1   Online        6 non-null      int64
 2   U prodavnici  6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 272.0+ bytes

In [56]:
pivot_table['Total'] = pivot_table['Online']+pivot_table['U prodavnici']
pivot_table

     Proizvod  Online  U prodavnici  Total
0      Ananas      70            90    160
1      Banana      90           110    200
2      Jabuka     100           150    250
3        Kivi      80           100    180
4      Kruška     120           130    250
5  Pomorandža      80           100    180

In [57]:
melt_table = pd.melt(pivot_table, id_vars = 'Proizvod', value_vars = ["Online","U prodavnici","Total"], var_name = "Tip prodaje",value_name = "Cena")