In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('movies_new.csv')

In [3]:
movies.head()

,name,year,genre,rating,summary,stars,votes,runtime,gross
0,Blood Red Sky,(2021),"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,Director: Peter Thorwarth | Stars: Peri B...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"Stars: Chris Wood, Sarah Michelle Gellar, Le...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars: Andrew Lincoln, Norman Reedus, Meliss...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"Stars: Justin Roiland, Chris Parnell, Spence...","414,849",23.0,NaN
4,Army of Thieves,(2021),"Action, Crime, Horror",NaN,"A prequel, set before the events of Army of th...",Director: Matthias Schweighöfer | Stars: ...,NaN,NaN,NaN

## Rad sa duplikatima

In [4]:
movies['name'].duplicated(keep=False)

0       False
1       False
2       False
3       False
4       False
        ...
9994     True
9995    False
9996    False
9997     True
9998     True
Name: name, Length: 9999, dtype: bool

In [5]:
movies[movies['name'].duplicated(keep='last')].sort_values('name')

,name,year,genre,rating,summary,stars,votes,runtime,gross
8375,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",5.6,As the school gears up for the Love Is Love da...,Director: Michael Sucsy | Stars: Dylan Mi...,"1,635",59.0,NaN
8395,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",6.8,When the dean begins a new investigation and t...,Director: Tommy Lohmann | Stars: Dylan Mi...,"1,640",60.0,NaN
8376,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",5.9,Clay's mental health continues to decline as t...,Director: Sunu Gonera | Stars: Dylan Minn...,"1,420",60.0,NaN
7378,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",5.7,"The police question Tyler about the guns, leav...",Director: Russell Mulcahy | Stars: Dylan ...,"1,798",59.0,NaN
7423,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",5.7,"After an incident at school, Clay thinks someo...",Director: Russell Mulcahy | Stars: Dylan ...,"1,597",58.0,NaN
...,...,...,...,...,...,...,...,...,...
1889,Ultraman,(2019– ),"Animation, Action, Adventure",6.9,Shinjiro Hayata learns that his father passed ...,"Stars: Ryohei Kimura, Josh Hutcherson, Takuy...","1,688",25.0,NaN
611,Undercover,(2019– ),"Crime, Drama, Thriller",7.8,"Inspired by real events, undercover agents inf...","Stars: Tom Waes, Frank Lammers, Manou Kersti...","12,708",50.0,NaN
1039,Verónica,(I) (2017),Horror,6.2,"Madrid, 1991. A teen girl finds herself besieg...",Director: Paco Plaza | Stars: Sandra Esca...,"37,751",105.0,NaN
1322,Wanderlust,(2018– ),Drama,7.1,A therapist tries to save her marriage after a...,"Stars: Toni Collette, Steven Mackintosh, Joe...","4,825",60.0,NaN
1527,Wednesday,(II),"Comedy, Family, Fantasy",NaN,A modernized live-action version of 'The Addam...,Star: Jenna Ortega,NaN,NaN,NaN

In [6]:
columns = ['name','year','rating','summary']
movies[movies[columns].duplicated(keep=False)].sort_values("name")

,name,year,genre,rating,summary,stars,votes,runtime,gross
9443,1899,(2022– ),"Drama, History, Horror",NaN,Add a Plot,Director: Baran bo Odar | Stars: Aneurin ...,NaN,NaN,NaN
9980,1899,(2022– ),"Drama, History, Horror",NaN,Add a Plot,Director: Baran bo Odar,NaN,NaN,NaN
9981,1899,(2022– ),"Drama, History, Horror",NaN,Add a Plot,Director: Baran bo Odar,NaN,NaN,NaN
9982,1899,(2022– ),"Drama, History, Horror",NaN,Add a Plot,Director: Baran bo Odar,NaN,NaN,NaN
9989,1899,(2022– ),"Drama, History, Horror",NaN,Add a Plot,Director: Baran bo Odar,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9977,Élite,(2018– ),"Crime, Drama, Thriller",NaN,Add a Plot,"Stars: Georgina Amorós, Carla Díaz, Martina ...",NaN,NaN,NaN
9948,Élite,(2018– ),"Crime, Drama, Thriller",NaN,Add a Plot,"Stars: Georgina Amorós, Carla Díaz, Martina ...",NaN,NaN,NaN
8373,Élite,(2018– ),"Crime, Drama, Thriller",NaN,Add a Plot,"Stars: Claudia Salas, Georgina Amorós, Carla...",NaN,NaN,NaN
9936,Élite,(2018– ),"Crime, Drama, Thriller",NaN,Add a Plot,"Stars: Itzan Escamilla, Omar Ayuso, Claudia ...",NaN,NaN,NaN
9949,Élite,(2018– ),"Crime, Drama, Thriller",NaN,Add a Plot,"Stars: Georgina Amorós, Carla Díaz, Martina ...",NaN,NaN,NaN

In [7]:
movies[movies[columns].duplicated(keep='first')].shape

(703, 9)

In [8]:
movies.shape

(9999, 9)

In [9]:
drop_all_duplicates_movies =  movies.drop_duplicates()

In [10]:
drop_all_duplicates_movies.shape

(9568, 9)

In [11]:
no_real_duplicates = movies.drop_duplicates(columns,keep='first')
no_real_duplicates.shape

(9296, 9)

## Nedostajuci podaci

In [12]:
movies = no_real_duplicates
movies.head()

,name,year,genre,rating,summary,stars,votes,runtime,gross
0,Blood Red Sky,(2021),"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,Director: Peter Thorwarth | Stars: Peri B...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"Stars: Chris Wood, Sarah Michelle Gellar, Le...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars: Andrew Lincoln, Norman Reedus, Meliss...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"Stars: Justin Roiland, Chris Parnell, Spence...","414,849",23.0,NaN
4,Army of Thieves,(2021),"Action, Crime, Horror",NaN,"A prequel, set before the events of Army of th...",Director: Matthias Schweighöfer | Stars: ...,NaN,NaN,NaN

In [13]:
movies['year'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
9976    False
9979    False
9993    False
9995    False
9996    False
Name: year, Length: 9296, dtype: bool

In [14]:
movies[movies['year'].isna()]

,name,year,genre,rating,summary,stars,votes,runtime,gross
878,Vikings: Valhalla,NaN,"Action, Adventure, Drama",NaN,Follow-up series to 'Vikings' set 100 years af...,"Stars: Laura Berlin, Sam Corlett, Bradley Fr...",NaN,NaN,NaN
1375,Resident Evil,NaN,"Action, Horror, Sci-Fi",NaN,Nearly three decades after the discovery of th...,"Stars: Lance Reddick, Siena Agudong, Ella Ba...",NaN,NaN,NaN
1414,Bright 2,NaN,"Action, Adventure, Crime",NaN,Plot unknown. Sequel to the 2017 film 'Bright.',"Stars: Will Smith, Joel Edgerton",NaN,NaN,NaN
1419,Avatar: The Last Airbender,NaN,"Action, Adventure, Fantasy",NaN,Live-action adaptation of the animated series ...,NaN,NaN,NaN,NaN
1425,Home Team,NaN,"Comedy, Sport",NaN,The story about New Orleans Saints head coach ...,"Directors: Charles Francis Kinnane, Daniel Ki...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9659,Yeh Kaali Kaali Ankhein,NaN,"Action, Drama, Romance",NaN,Add a Plot,"Directors: Rohit Jugraj, Siddharth Sengupta |...",NaN,NaN,NaN
9736,From Scratch,NaN,Drama,NaN,Add a Plot,Director: Nzingha Stewart | Stars: Antoni...,NaN,NaN,NaN
9781,Inside Man,NaN,"Drama, Mystery, Thriller",NaN,Add a Plot,Director: Paul McGuigan | Stars: July Nam...,NaN,NaN,NaN
9836,Kus uçusu,NaN,Comedy,NaN,Add a Plot,Director: Deniz Yorulmazer | Stars: Birce...,NaN,NaN,NaN
9904,Pretty Smart,NaN,Comedy,NaN,Add a Plot,Director: Pamela Fryman | Stars: Cinthya ...,NaN,NaN,NaN

In [15]:
movies.isna().sum()

name          0
year        482
genre        78
rating     1197
summary       0
stars       381
votes      1197
runtime    2313
gross      8836
dtype: int64

In [16]:
movies.shape

(9296, 9)

## Brisanje nedostajucih podataka

In [17]:
movies = movies.drop('gross', axis = 1)

In [18]:
movies.head()

,name,year,genre,rating,summary,stars,votes,runtime
0,Blood Red Sky,(2021),"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,Director: Peter Thorwarth | Stars: Peri B...,"21,062",121.0
1,Masters of the Universe: Revelation,(2021– ),"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"Stars: Chris Wood, Sarah Michelle Gellar, Le...","17,870",25.0
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars: Andrew Lincoln, Norman Reedus, Meliss...","885,805",44.0
3,Rick and Morty,(2013– ),"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"Stars: Justin Roiland, Chris Parnell, Spence...","414,849",23.0
4,Army of Thieves,(2021),"Action, Crime, Horror",NaN,"A prequel, set before the events of Army of th...",Director: Matthias Schweighöfer | Stars: ...,NaN,NaN

In [19]:
drop_all_na = movies.copy()

In [20]:
drop_all_na = drop_all_na.dropna()

In [21]:
drop_all_na.shape

(6727, 8)

In [22]:
movies = movies.dropna(subset = ['year','genre','stars'])

In [23]:
movies.shape

(8596, 8)

In [24]:
movies.isna().sum()

name          0
year          0
genre         0
rating      591
summary       0
stars         0
votes       591
runtime    1691
dtype: int64

## Popunjavanje nedostajucih podataka

## Numericki podaci

In [25]:
movies[movies['rating'].isna()]

,name,year,genre,rating,summary,stars,votes,runtime
4,Army of Thieves,(2021),"Action, Crime, Horror",NaN,"A prequel, set before the events of Army of th...",Director: Matthias Schweighöfer | Stars: ...,NaN,NaN
214,Sing 2,(2021),"Animation, Adventure, Comedy",NaN,Buster Moon and his friends must persuade recl...,Director: Garth Jennings | Stars: Matthew...,NaN,NaN
217,Knives Out 2,(2022),"Comedy, Crime, Drama",NaN,Plot unknown. Sequel to the 2019 film 'Knives ...,Director: Rian Johnson | Stars: Madelyn C...,NaN,NaN
222,Don't Look Up,(2021),Comedy,NaN,"The story of two low-level astronomers, who mu...",Director: Adam McKay | Stars: Timothée Ch...,NaN,145.0
236,Red Notice,(2021),"Action, Comedy, Crime",NaN,An Interpol agent tracks the world's most want...,Director: Rawson Marshall Thurber | Stars...,NaN,NaN
...,...,...,...,...,...,...,...,...
9964,AlRawabi School for Girls,(2021),Drama,NaN,Add a Plot,Director: Tima Shomali | Stars: Salsabiel...,NaN,NaN
9975,Ultraman,(2019– ),"Animation, Action, Adventure",NaN,Add a Plot,"Stars: Ryohei Kimura, Josh Hutcherson",NaN,NaN
9976,The Talk,(2010– ),Talk-Show,NaN,"Actor Brian Tyree Henry (""Godzilla vs. Kong"", ...","Stars: Sheryl Underwood, Carrie Ann Inaba, A...",NaN,38.0
9993,Totenfrau,(2022– ),"Drama, Thriller",NaN,Add a Plot,Director: Nicolai Rohde | Stars: Felix Kl...,NaN,NaN
9996,Heart of Invictus,(2022– ),"Documentary, Sport",NaN,Add a Plot,Director: Orlando von Einsiedel | Star: P...,NaN,NaN

### Popunjavanje kolone Rating

In [26]:
movies.iloc[4]

name                                         Army of Thieves
year                                                  (2021)
genre                      Action, Crime, Horror
rating                                                   NaN
summary    A prequel, set before the events of Army of th...
stars      Director: Matthias Schweighöfer |      Stars: ...
votes                                                    NaN
runtime                                                  NaN
Name: 4, dtype: object

In [27]:
mean_of_rating = round(movies['rating'].mean(),1)
mean_of_rating

6.9

In [28]:
movies['rating'] = movies['rating'].fillna(mean_of_rating)

In [29]:
movies.iloc[4]

name                                         Army of Thieves
year                                                  (2021)
genre                      Action, Crime, Horror
rating                                                   6.9
summary    A prequel, set before the events of Army of th...
stars      Director: Matthias Schweighöfer |      Stars: ...
votes                                                    NaN
runtime                                                  NaN
Name: 4, dtype: object

## Popunjavanje kolona Votes, Runtime

In [30]:
movies.isna().sum()

name          0
year          0
genre         0
rating        0
summary       0
stars         0
votes       591
runtime    1691
dtype: int64

In [31]:
movies['votes'] = movies['votes'].fillna(0)

In [32]:
movies.iloc[4]

name                                         Army of Thieves
year                                                  (2021)
genre                      Action, Crime, Horror
rating                                                   6.9
summary    A prequel, set before the events of Army of th...
stars      Director: Matthias Schweighöfer |      Stars: ...
votes                                                      0
runtime                                                  NaN
Name: 4, dtype: object

In [33]:
mean_of_runtime = round(movies['runtime'].mean(),0)
mean_of_runtime

69.0

In [34]:
movies['runtime'] = movies['runtime'].fillna(mean_of_runtime)

In [35]:
movies.iloc[4]

name                                         Army of Thieves
year                                                  (2021)
genre                      Action, Crime, Horror
rating                                                   6.9
summary    A prequel, set before the events of Army of th...
stars      Director: Matthias Schweighöfer |      Stars: ...
votes                                                      0
runtime                                                 69.0
Name: 4, dtype: object

In [36]:
movies.isna().sum()

name       0
year       0
genre      0
rating     0
summary    0
stars      0
votes      0
runtime    0
dtype: int64

## Kategoricki podaci

In [37]:
airbnb = pd.read_csv('new_airbnb.csv')

In [38]:
columns_to_keep = ['id',  'name', 'summary',  'description',
        'host_name', 'host_is_superhost',
       'street', 'neighbourhood', 
       'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
        'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities',
       'price', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights',
       'number_of_reviews', 'review_scores_rating', 'cancellation_policy']

In [39]:
airbnb = airbnb[columns_to_keep]

In [40]:
airbnb.head()

,id,name,summary,description,host_name,host_is_superhost,street,neighbourhood,city,state,...,bed_type,amenities,price,guests_included,extra_people,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,cancellation_policy
0,12147973,Sunny Bungalow in the City of Boston,"Cozy, sunny, family home. Master bedroom high...","Cozy, sunny, family home. Master bedroom high...",Virginia,f,"Birch Street, Boston, MA 02131, United States",Roslindale,Boston,MA,...,Real Bed,"{TV,""Wireless Internet"",Kitchen,""Free Parking ...",250.0,1,$0.00,2,1125,0,NaN,moderate
1,3075044,Charming room in pet friendly apt,Charming and quiet room in a second floor 1910...,Charming and quiet room in a second floor 1910...,Andrea,f,"Pinehurst Street, Boston, MA 02131, United States",Roslindale,Boston,MA,...,Real Bed,"{TV,Internet,""Wireless Internet"",""Air Conditio...",65.0,0,$0.00,2,15,36,94.0,moderate
2,6976,Mexican Folk Art Haven in Boston,"Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...",Phil,t,"Ardale St., Boston, MA 02131, United States",Roslindale,Boston,MA,...,Real Bed,"{TV,""Cable TV"",""Wireless Internet"",""Air Condit...",65.0,1,$20.00,3,45,41,98.0,moderate
3,1436513,Spacious Sunny Bedroom Suite in Historic Home,Come experience the comforts of home away from...,Come experience the comforts of home away from...,Meghna,f,"Boston, MA, United States",NaN,Boston,MA,...,Real Bed,"{TV,Internet,""Wireless Internet"",""Air Conditio...",75.0,2,$25.00,1,1125,1,100.0,moderate
4,7651065,Come Home to Boston,"My comfy, clean and relaxing home is one block...","My comfy, clean and relaxing home is one block...",Linda,t,"Durnell Avenue, Boston, MA 02131, United States",Roslindale,Boston,MA,...,Real Bed,"{Internet,""Wireless Internet"",""Air Conditionin...",79.0,1,$0.00,2,31,29,99.0,flexible

In [41]:
airbnb[airbnb[['name','longitude','latitude']].duplicated(keep=False)]

Empty DataFrame
Columns: [id, name, summary, description, host_name, host_is_superhost, street, neighbourhood, city, state, zipcode, market, smart_location, country_code, country, latitude, longitude, property_type, room_type, accommodates, bathrooms, bedrooms, beds, bed_type, amenities, price, guests_included, extra_people, minimum_nights, maximum_nights, number_of_reviews, review_scores_rating, cancellation_policy]
Index: []

[0 rows x 33 columns]

In [42]:
airbnb.isna().sum()

id                        0
name                      0
summary                 143
description               0
host_name                 0
host_is_superhost         0
street                    0
neighbourhood           543
city                      2
state                     0
zipcode                  38
market                   14
smart_location            0
country_code              0
country                   0
latitude                  0
longitude                 0
property_type             3
room_type                 0
accommodates              0
bathrooms                14
bedrooms                 10
beds                      9
bed_type                  0
amenities                 0
price                     0
guests_included           0
extra_people              0
minimum_nights            0
maximum_nights            0
number_of_reviews         0
review_scores_rating    813
cancellation_policy       0
dtype: int64

## Popunjavanja kolone property type

In [43]:
airbnb.property_type.value_counts()

Apartment          2612
House               562
Condominium         231
Townhouse            54
Bed & Breakfast      41
Loft                 39
Other                17
Boat                 12
Villa                 6
Entire Floor          4
Dorm                  2
Guesthouse            1
Camper/RV             1
Name: property_type, dtype: int64

In [44]:
airbnb['property_type'].mode()

0    Apartment
Name: property_type, dtype: object

In [45]:
mode_of_property_type = airbnb['property_type'].mode()[0]

In [46]:
mode_of_property_type

'Apartment'

In [47]:
airbnb['property_type'] = airbnb['property_type'].fillna(mode_of_property_type)

In [48]:
airbnb.isna().sum()

id                        0
name                      0
summary                 143
description               0
host_name                 0
host_is_superhost         0
street                    0
neighbourhood           543
city                      2
state                     0
zipcode                  38
market                   14
smart_location            0
country_code              0
country                   0
latitude                  0
longitude                 0
property_type             0
room_type                 0
accommodates              0
bathrooms                14
bedrooms                 10
beds                      9
bed_type                  0
amenities                 0
price                     0
guests_included           0
extra_people              0
minimum_nights            0
maximum_nights            0
number_of_reviews         0
review_scores_rating    813
cancellation_policy       0
dtype: int64

### Popunjavanje kolone review scores rating

In [49]:
airbnb['review_scores_rating'].head()

0      NaN
1     94.0
2     98.0
3    100.0
4     99.0
Name: review_scores_rating, dtype: float64

In [50]:
mean_of_review = round(airbnb['review_scores_rating'].mean(),0)
mean_of_review

92.0

In [51]:
airbnb['review_scores_rating'] = airbnb['review_scores_rating'].fillna(mean_of_review)

In [52]:
airbnb['review_scores_rating'].head()

0     92.0
1     94.0
2     98.0
3    100.0
4     99.0
Name: review_scores_rating, dtype: float64

## Popunjavanje kolona beds, bedrooms, bathrooms

In [53]:
airbnb['bathrooms'] = airbnb['bathrooms'].fillna(1)

In [54]:
beds_na = airbnb[airbnb['beds'].isna()]

In [55]:
beds_na.accommodates

494     1
755     2
820     2
825     2
910     1
2203    1
2819    2
2865    2
3557    2
Name: accommodates, dtype: int64

In [56]:
for index, row in airbnb[airbnb['beds'].isna()].iterrows():
    print(index,row)
    if row['accommodates'] ==1:
        airbnb.at[index, 'beds'] = 1
    else:
        airbnb.at[index, 'beds'] = 2

494 id                                                               14336348
name                         4 minutes walk to the Longwood Medical Area.
summary                 My place is close to The Longwood Medical Area...
description             My place is close to The Longwood Medical Area...
host_name                                                          Khaled
host_is_superhost                                                       f
street                                          Boston, MA, United States
neighbourhood                                                         NaN
city                                                               Boston
state                                                                  MA
zipcode                                                               NaN
market                                                             Boston
smart_location                                                 Boston, MA
country_code                                                           US
country                                                     United States
latitude                                                        42.333072
longitude                                                      -71.101286
property_type                                                   Apartment
room_type                                                    Private room
accommodates                                                            1
bathrooms                                                             1.0
bedrooms                                                              1.0
beds                                                                  NaN
bed_type                                                         Real Bed
amenities               {"Wireless Internet","Air Conditioning",Kitche...
price                                                                99.0
guests_included                                                         1
extra_people                                                       $50.00
minimum_nights                                                          2
maximum_nights                                                         23
number_of_reviews                                                       1
review_scores_rating                                                100.0
cancellation_policy                                              moderate
Name: 494, dtype: object
755 id                                                                1426754
name                                   Boston Best furnished Studio (H2a)
summary                                                               NaN
description             Studio in excellent location, 2nd floor walk u...
host_name                                                            Dror
host_is_superhost                                                       f
street                    Hanover Street, Boston, MA 02108, United States
neighbourhood                                                   North End
city                                                               Boston
state                                                                  MA
zipcode                                                             02108
market                                                             Boston
smart_location                                                 Boston, MA
country_code                                                           US
country                                                     United States
latitude                                                        42.364824
longitude                                                      -71.053707
property_type                                                   Apartment
room_type                                                 Entire home/apt
accommodates                                                            2
bathrooms                                                             1.0
bedrooms                                                              1.0
beds                                                                  NaN
bed_type                                                         Real Bed
amenities               {TV,"Cable TV",Internet,"Wireless Internet","A...
price                                                                99.0
guests_included                                                         1
extra_people                                                        $0.00
minimum_nights                                                          1
maximum_nights                                                        365
number_of_reviews                                                      73
review_scores_rating                                                 91.0
cancellation_policy                                                strict
Name: 755, dtype: object
820 id                                                               12627225
name                                   Local BedNBreakfast Mins 2 Dwntown
summary                 Great local BednBreakfast minutes from Dwntown...
description             Great local BednBreakfast minutes from Dwntown...
host_name                                                         Kaitlin
host_is_superhost                                                       f
street                    Gayland Street, Boston, MA 02125, United States
neighbourhood                                                         NaN
city                                                               Boston
state                                                                  MA
zipcode                                                             02125
market                                                             Boston
smart_location                                                 Boston, MA
country_code                                                           US
country                                                     United States
latitude                                                        42.321037
longitude                                                      -71.074579
property_type                                             Bed & Breakfast
room_type                                                    Private room
accommodates                                                            2
bathrooms                                                             1.0
bedrooms                                                              1.0
beds                                                                  NaN
bed_type                                                         Real Bed
amenities               {"Air Conditioning","Free Parking on Premises"...
price                                                                60.0
guests_included                                                         1
extra_people                                                       $20.00
minimum_nights                                                          1
maximum_nights                                                       1125
number_of_reviews                                                      10
review_scores_rating                                                 58.0
cancellation_policy                                                strict
Name: 820, dtype: object
825 id                                                               12857811
name                                    Local BednBreakfast Nxt 2 Dwntown
summary                 Great local BednBreakfast minutes from Dwntown...
description             Great local BednBreakfast minutes from Dwntown...
host_name                                                         Kaitlin
host_is_superhost                                                       f
street                    Gayland Street, Boston, MA 02125, United States
neighbourhood                                                         NaN
city                                                               Boston
state                                                                  MA
zipcode                                                             02125
market                                                             Boston
smart_location                                                 Boston, MA
country_code                                                           US
country                                                     United States
latitude                                                         42.31877
longitude                                                      -71.077602
property_type                                                       House
room_type                                                    Private room
accommodates                                                            2
bathrooms                                                             1.0
bedrooms                                                              1.0
beds                                                                  NaN
bed_type                                                         Real Bed
amenities               {TV,"Air Conditioning","Free Parking on Premis...
price                                                                60.0
guests_included                                                         1
extra_people                                                       $20.00
minimum_nights                                                          1
maximum_nights                                                       1125
number_of_reviews                                                      14
review_scores_rating                                                 62.0
cancellation_policy                                              flexible
Name: 825, dtype: object
910 id                                                               12796808
name                                               Northeastern sweet pad
summary                 Sweet pad just steps away from Northeastern Un...
description             Sweet pad just steps away from Northeastern Un...
host_name                                                           Jason
host_is_superhost                                                       f
street                     Centre Street, Boston, MA 02119, United States
neighbourhood                                                         NaN
city                                                               Boston
state                                                                  MA
zipcode                                                             02119
market                                                             Boston
smart_location                                                 Boston, MA
country_code                                                           US
country                                                     United States
latitude                                                        42.328606
longitude                                                       -71.09176
property_type                                                   Apartment
room_type                                                    Private room
accommodates                                                            1
bathrooms                                                             1.0
bedrooms                                                              1.0
beds                                                                  NaN
bed_type                                                         Real Bed
amenities                                                              {}
price                                                                53.0
guests_included                                                         1
extra_people                                                        $0.00
minimum_nights                                                          1
maximum_nights                                                       1125
number_of_reviews                                                       0
review_scores_rating                                                 92.0
cancellation_policy                                              flexible
Name: 910, dtype: object
2203 id                                                                8152796
name                                     A very clean place nearby subway
summary                 This is a clean bedroom. My house is nearby th...
description             This is a clean bedroom. My house is nearby th...
host_name                                                            Ryan
host_is_superhost                                                       f
street                   Westland Avenue, Boston, MA 02115, United States
neighbourhood                                              Fenway/Kenmore
city                                                               Boston
state                                                                  MA
zipcode                                                             02115
market                                                             Boston
smart_location                                                 Boston, MA
country_code                                                           US
country                                                     United States
latitude                                                        42.343241
longitude                                                      -71.086783
property_type                                                   Apartment
room_type                                                    Private room
accommodates                                                            1
bathrooms                                                             1.0
bedrooms                                                              1.0
beds                                                                  NaN
bed_type                                                         Real Bed
amenities               {"Wireless Internet","Air Conditioning","Eleva...
price                                                                80.0
guests_included                                                         1
extra_people                                                        $0.00
minimum_nights                                                          1
maximum_nights                                                         10
number_of_reviews                                                       0
review_scores_rating                                                 92.0
cancellation_policy                                              flexible
Name: 2203, dtype: object
2819 id                                                                9239190
name                                  Spacious rooms minutes from Ashmont
summary                 Large well furnished clean rooms on a quiet si...
description             Large well furnished clean rooms on a quiet si...
host_name                                                            Jose
host_is_superhost                                                       f
street                   Lonsdale Street, Boston, MA 02124, United States
neighbourhood                                                  Dorchester
city                                                               Boston
state                                                                  MA
zipcode                                                             02124
market                                                             Boston
smart_location                                                 Boston, MA
country_code                                                           US
country                                                     United States
latitude                                                        42.290891
longitude                                                      -71.060188
property_type                                                       House
room_type                                                    Private room
accommodates                                                            2
bathrooms                                                             1.0
bedrooms                                                              1.0
beds                                                                  NaN
bed_type                                                         Real Bed
amenities               {Internet,"Wireless Internet",Kitchen,"Pets li...
price                                                                57.0
guests_included                                                         1
extra_people                                                       $12.00
minimum_nights                                                          1
maximum_nights                                                       1125
number_of_reviews                                                      12
review_scores_rating                                                 87.0
cancellation_policy                                              flexible
Name: 2819, dtype: object
2865 id                                                               12857981
name                                     Local BedNBreafast Nxt 2 Dwntown
summary                 Great local BednBreakfast minutes from Dwntown...
description             Great local BednBreakfast minutes from Dwntown...
host_name                                                         Kaitlin
host_is_superhost                                                       f
street                        Gayland St, Boston, MA 02125, United States
neighbourhood                                                         NaN
city                                                               Boston
state                                                                  MA
zipcode                                                             02125
market                                                             Boston
smart_location                                                 Boston, MA
country_code                                                           US
country                                                     United States
latitude                                                        42.302353
longitude                                                      -71.065605
property_type                                                       House
room_type                                                    Private room
accommodates                                                            2
bathrooms                                                             1.0
bedrooms                                                              1.0
beds                                                                  NaN
bed_type                                                         Real Bed
amenities               {Internet,"Air Conditioning",Kitchen,"Free Par...
price                                                                60.0
guests_included                                                         1
extra_people                                                       $20.00
minimum_nights                                                          1
maximum_nights                                                       1125
number_of_reviews                                                       3
review_scores_rating                                                 93.0
cancellation_policy                                                strict
Name: 2865, dtype: object
3557 id                                                               14604429
name                        Bedroom in to Allston/Brookline area for rent

In [57]:
airbnb.isna().sum()

id                        0
name                      0
summary                 143
description               0
host_name                 0
host_is_superhost         0
street                    0
neighbourhood           543
city                      2
state                     0
zipcode                  38
market                   14
smart_location            0
country_code              0
country                   0
latitude                  0
longitude                 0
property_type             0
room_type                 0
accommodates              0
bathrooms                 0
bedrooms                 10
beds                      0
bed_type                  0
amenities                 0
price                     0
guests_included           0
extra_people              0
minimum_nights            0
maximum_nights            0
number_of_reviews         0
review_scores_rating      0
cancellation_policy       0
dtype: int64

In [58]:
for index, row in airbnb[airbnb['bedrooms'].isna()].iterrows():
    if row['beds'] ==1:
        airbnb.at[index, 'bedrooms'] = 0
    if row['beds'] ==2:
        airbnb.at[index, 'bedrooms'] = 1
    else:
        airbnb.at[index, 'bedrooms'] = 2

In [59]:
for index, row in airbnb[airbnb['summary'].isna()].iterrows():
    summary = row['room_type'] + ' with ' +str(row['beds'])+' beds in ' + str(row['state'])
    airbnb.at[index,'summary'] = summary

In [60]:
airbnb.isna().sum()

id                        0
name                      0
summary                   0
description               0
host_name                 0
host_is_superhost         0
street                    0
neighbourhood           543
city                      2
state                     0
zipcode                  38
market                   14
smart_location            0
country_code              0
country                   0
latitude                  0
longitude                 0
property_type             0
room_type                 0
accommodates              0
bathrooms                 0
bedrooms                  0
beds                      0
bed_type                  0
amenities                 0
price                     0
guests_included           0
extra_people              0
minimum_nights            0
maximum_nights            0
number_of_reviews         0
review_scores_rating      0
cancellation_policy       0
dtype: int64

### Popunjavanje kolona vezenih za lokaciju

In [61]:
airbnb.market.value_counts()

Boston                   3568
San Francisco               1
Other (Domestic)            1
Other (International)       1
Name: market, dtype: int64

In [62]:
airbnb = airbnb.drop(columns = ['market','city'],axis = 1)

In [63]:
airbnb.isna().sum()

id                        0
name                      0
summary                   0
description               0
host_name                 0
host_is_superhost         0
street                    0
neighbourhood           543
state                     0
zipcode                  38
smart_location            0
country_code              0
country                   0
latitude                  0
longitude                 0
property_type             0
room_type                 0
accommodates              0
bathrooms                 0
bedrooms                  0
beds                      0
bed_type                  0
amenities                 0
price                     0
guests_included           0
extra_people              0
minimum_nights            0
maximum_nights            0
number_of_reviews         0
review_scores_rating      0
cancellation_policy       0
dtype: int64

In [64]:
airbnb[['longitude','latitude']].head()

   longitude   latitude
0 -71.133068  42.282619
1 -71.134374  42.286241
2 -71.135765  42.292438
3 -71.121021  42.281106
4 -71.136258  42.284512

In [65]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3585 entries, 0 to 3584
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    3585 non-null   int64
 1   name                  3585 non-null   object
 2   summary               3585 non-null   object
 3   description           3585 non-null   object
 4   host_name             3585 non-null   object
 5   host_is_superhost     3585 non-null   object
 6   street                3585 non-null   object
 7   neighbourhood         3042 non-null   object
 8   state                 3585 non-null   object
 9   zipcode               3547 non-null   object
 10  smart_location        3585 non-null   object
 11  country_code          3585 non-null   object
 12  country               3585 non-null   object
 13  latitude              3585 non-null   float64
 14  longitude             3585 non-null   float64
 15  property_type         3585 non-null   object
 16  room_type             3585 non-null   object
 17  accommodates          3585 non-null   int64
 18  bathrooms             3585 non-null   float64
 19  bedrooms              3585 non-null   float64
 20  beds                  3585 non-null   float64
 21  bed_type              3585 non-null   object
 22  amenities             3585 non-null   object
 23  price                 3585 non-null   float64
 24  guests_included       3585 non-null   int64
 25  extra_people          3585 non-null   object
 26  minimum_nights        3585 non-null   int64
 27  maximum_nights        3585 non-null   int64
 28  number_of_reviews     3585 non-null   int64
 29  review_scores_rating  3585 non-null   float64
 30  cancellation_policy   3585 non-null   object
dtypes: float64(7), int64(6), object(18)
memory usage: 868.4+ KB

In [66]:
# import module
from geopy.geocoders import Nominatim
 
# initialize Nominatim API
geolocator = Nominatim(user_agent="data analysis course")
 
 
# Latitude & Longitude input
Latitude = "42.282619"
Longitude = "-71.133068"
 
location = geolocator.reverse(Latitude+","+Longitude)
 
address = location.raw['address']
 
print(address.get('suburb'))

Roslindale

In [67]:
# traverse the data
city = address.get('city', '')
state = address.get('state', '')
country = address.get('country', '')
code = address.get('country_code')
zipcode = address.get('postcode')
print('City : ', city)
print('State : ', state)
print('Country : ', country)
print('Zip Code : ', zipcode)

City :  Boston
State :  Massachusetts
Country :  United States
Zip Code :  02131

In [68]:
airbnb[airbnb['neighbourhood'].isna()].head()

,id,name,summary,description,host_name,host_is_superhost,street,neighbourhood,state,zipcode,...,bed_type,amenities,price,guests_included,extra_people,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,cancellation_policy
3,1436513,Spacious Sunny Bedroom Suite in Historic Home,Come experience the comforts of home away from...,Come experience the comforts of home away from...,Meghna,f,"Boston, MA, United States",NaN,MA,NaN,...,Real Bed,"{TV,Internet,""Wireless Internet"",""Air Conditio...",75.0,2,$25.00,1,1125,1,100.0,moderate
6,5706985,New Lrg Studio apt 15 min to Boston,It's a 5 minute walk to Rosi Square to catch t...,It's a 5 minute walk to Rosi Square to catch t...,Juliet,f,"Kittredge Street, Boston, MA 02131, United States",NaN,MA,02131,...,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",100.0,1,$25.00,1,1125,57,90.0,strict
19,7252607,Private Room near Public Transport,A handsome colonial house set on a tranquil si...,A handsome colonial house set on a tranquil si...,Barrie,t,"Brook St, Boston, MA 02131, United States",NaN,MA,02131,...,Real Bed,"{TV,Internet,""Wireless Internet"",""Air Conditio...",49.0,1,$10.00,5,1125,4,95.0,strict
23,6400432,Spacious 3 bedroom cape cod style,Three bedroom in Boston's Roslindale neighborh...,Three bedroom in Boston's Roslindale neighborh...,Jesús,f,"Metropolitan Ave, Boston, MA 02131, United States",NaN,MA,02131,...,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",150.0,6,$0.00,3,1125,21,88.0,flexible
36,10116095,Comfortable & Clean - Boston,Comfortable private room with a queen sized be...,Comfortable private room with a queen sized be...,Jim,f,"Sheffield Road, Boston, MA 02131, United States",NaN,MA,02131,...,Real Bed,"{TV,""Wireless Internet"",Kitchen,""Free Parking ...",115.0,1,$0.00,1,1125,0,92.0,strict

In [69]:
airbnb.iloc[3]

id                                                                1436513
name                        Spacious Sunny Bedroom Suite in Historic Home
summary                 Come experience the comforts of home away from...
description             Come experience the comforts of home away from...
host_name                                                          Meghna
host_is_superhost                                                       f
street                                          Boston, MA, United States
neighbourhood                                                         NaN
state                                                                  MA
zipcode                                                               NaN
smart_location                                                 Boston, MA
country_code                                                           US
country                                                     United States
latitude                                                        42.281106
longitude                                                      -71.121021
property_type                                                       House
room_type                                                    Private room
accommodates                                                            4
bathrooms                                                             1.0
bedrooms                                                              1.0
beds                                                                  2.0
bed_type                                                         Real Bed
amenities               {TV,Internet,"Wireless Internet","Air Conditio...
price                                                                75.0
guests_included                                                         2
extra_people                                                       $25.00
minimum_nights                                                          1
maximum_nights                                                       1125
number_of_reviews                                                       1
review_scores_rating                                                100.0
cancellation_policy                                              moderate
Name: 3, dtype: object

In [70]:
def lokacija(latitude,longitude):
    from geopy.geocoders import Nominatim
    geolocator = Nominatim(user_agent="data analysis course")
    location = geolocator.reverse(latitude+","+longitude)
    address = location.raw['address']
    return address.get('suburb')

In [72]:
for index,row in airbnb[airbnb['neighbourhood'].isna()].iterrows():
    airbnb.at[index,'neighbourhood'] = lokacija(str(row['latitude']),str(row['longitude']))

In [73]:
airbnb.iloc[3]

id                                                                1436513
name                        Spacious Sunny Bedroom Suite in Historic Home
summary                 Come experience the comforts of home away from...
description             Come experience the comforts of home away from...
host_name                                                          Meghna
host_is_superhost                                                       f
street                                          Boston, MA, United States
neighbourhood                                                  Roslindale
state                                                                  MA
zipcode                                                               NaN
smart_location                                                 Boston, MA
country_code                                                           US
country                                                     United States
latitude                                                        42.281106
longitude                                                      -71.121021
property_type                                                       House
room_type                                                    Private room
accommodates                                                            4
bathrooms                                                             1.0
bedrooms                                                              1.0
beds                                                                  2.0
bed_type                                                         Real Bed
amenities               {TV,Internet,"Wireless Internet","Air Conditio...
price                                                                75.0
guests_included                                                         2
extra_people                                                       $25.00
minimum_nights                                                          1
maximum_nights                                                       1125
number_of_reviews                                                       1
review_scores_rating                                                100.0
cancellation_policy                                              moderate
Name: 3, dtype: object

In [74]:
airbnb.isna().sum()

id                       0
name                     0
summary                  0
description              0
host_name                0
host_is_superhost        0
street                   0
neighbourhood           71
state                    0
zipcode                 38
smart_location           0
country_code             0
country                  0
latitude                 0
longitude                0
property_type            0
room_type                0
accommodates             0
bathrooms                0
bedrooms                 0
beds                     0
bed_type                 0
amenities                0
price                    0
guests_included          0
extra_people             0
minimum_nights           0
maximum_nights           0
number_of_reviews        0
review_scores_rating     0
cancellation_policy      0
dtype: int64

In [75]:
def lokacija(latitude,longitude):
    from geopy.geocoders import Nominatim
    geolocator = Nominatim(user_agent="data analysis course")
    location = geolocator.reverse(latitude+","+longitude)
    address = location.raw['address']
    return address.get('postcode')

In [76]:
for index,row in airbnb[airbnb['zipcode'].isna()].iterrows():
    airbnb.at[index,'zipcode'] = lokacija(str(row['latitude']),str(row['longitude']))

In [77]:
airbnb.isna().sum()

id                       0
name                     0
summary                  0
description              0
host_name                0
host_is_superhost        0
street                   0
neighbourhood           71
state                    0
zipcode                  0
smart_location           0
country_code             0
country                  0
latitude                 0
longitude                0
property_type            0
room_type                0
accommodates             0
bathrooms                0
bedrooms                 0
beds                     0
bed_type                 0
amenities                0
price                    0
guests_included          0
extra_people             0
minimum_nights           0
maximum_nights           0
number_of_reviews        0
review_scores_rating     0
cancellation_policy      0
dtype: int64

In [80]:
airbnb = airbnb.dropna()

In [81]:
airbnb.isna().sum()

id                      0
name                    0
summary                 0
description             0
host_name               0
host_is_superhost       0
street                  0
neighbourhood           0
state                   0
zipcode                 0
smart_location          0
country_code            0
country                 0
latitude                0
longitude               0
property_type           0
room_type               0
accommodates            0
bathrooms               0
bedrooms                0
beds                    0
bed_type                0
amenities               0
price                   0
guests_included         0
extra_people            0
minimum_nights          0
maximum_nights          0
number_of_reviews       0
review_scores_rating    0
cancellation_policy     0
dtype: int64

In [84]:
airbnb.to_csv('airbnb_clean_final.csv')